apiVersion: v1
kind: Pod
metadata:
  name: kubia
  labels:
    app: kubia-pod
spec:
  containers:
    - image: luksa/kubia
      name: kubia
      ports:
      - name: http
        containerPort: 8080