apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv-aws
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: aws://ap-northeast-2a/vol-
    fsType: ext4