apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
spec:
  containers:
    - name: mongo
      image: mongo
      volumeMounts:
        - mountPath: /data/db
          name: mongo-data
      ports:
        - containerPort: 27017
          protocol: TCP
  volumes:
    - name: mongo-data
      persistentVolumeClaim:
        claimName: mongodb-pvc