apiVersion: v1
kind: Pod
metadata:
  name: curl-custom-sa
spec:
  serviceAccount: foo
  containers:
    - name: curl
      image: curlimages/curl
      command: ["sleep", "infinity"]
    - name: ambassador
      image: bitnami/kubectl
      command: ["kubectl", "proxy"]