apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: foo
spec:
  containers:
    - name: curl
      image: curlimages/curl
      command: ["sleep", "infinity"]
    - name: ambassador
      image: bitnami/kubectl
      command: ["kubectl", "proxy"]
---
apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: bar
spec:
  containers:
    - name: curl
      image: curlimages/curl
      command: ["sleep", "infinity"]
    - name: ambassador
      image: bitnami/kubectl
      command: ["kubectl", "proxy"]