apiVersion: v1
kind: Pod
metadata:
  name: fortune
  labels:
    app: web-server
spec:
  containers:
    - name: web-server
      image: nginx:alpine
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html
          readOnly: true
      ports:
        - containerPort: 80
          protocol: TCP
    - name: fortune
      image: luksa/fortune
      volumeMounts:
        - mountPath: /var/htdocs
          name: html
  volumes:
    - name: html
      emptyDir:
        medium: Memory