apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: pod-with-port
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: kubia
        image: luksa/kubia
        ports:
          - containerPort: 8080
            name: http-alt