apiVersion: apps/v1
kind: Deployment
metadata:
  name: pref
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: availability-zone
                    operator: In
                    values:
                      - zone1
              weight: 80
            - preference:
                matchExpressions:
                  - key: share-type
                    operator: In
                    values:
                      - dedicated
              weight: 20
      containers:
        - name: main
          image: luksa/kubia